language: node_js

node_js:
  - node

addons:
  postgresql: "9.6"
  chrome: stable
  apt:
    sources:
      - mysql-5.7-trusty
#      - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial main'
#        key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - mysql-client
      - mysql-server
#      - mssql-server
#      - mssql-tools

services:
  - docker

before_install:
  - sudo mysql_upgrade
  - mysql -v -e "source test/mysql/db_create.sql"
  - mysql -v -e "source test/mysql/expecteddatamodel_table_create.sql"
  - psql -v ON_ERROR_STOP=1 --username postgres -f test/postgreqsl/db_create.sql
  - psql -v ON_ERROR_STOP=1 --username user -f test/postgreqsl/expecteddatamodel_table_create.sql
  - sudo chmod 777 /etc/postgresql/9.6/main/pg_hba.conf
  - sudo sed -i '/\bhost    all             all             127.0.0.1\/32            trust\b/i host    all             user            all                      md5' /etc/postgresql/9.6/main/pg_hba.conf
  - sudo chmod 640 /etc/postgresql/9.6/main/pg_hba.conf
  - sudo service postgresql restart 9.6
  - docker-compose -f test/mssql/docker-compose.yml up -d db
  - docker cp test/mssql/db_create.sql mssql_db_1:/tmp/db_create.sql
  - docker cp test/mssql/expecteddatamodel_table_create.sql mssql_db_1:/tmp/expecteddatamodel_table_create.sql
  - docker exec -it mssql_db_1 /opt/mssql-tools/bin/sqlcmd -e -S localhost -U sa -P password01@ -i /tmp/db_create.sql
  - docker exec -it mssql_db_1 /opt/mssql-tools/bin/sqlcmd -e -S localhost -U test_user -P password01@ -i /tmp/expecteddatamodel_table_create.sql

before_script:
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nyc --reporter=lcov npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false

before_deploy:
  - export PKG_NAME=$(node -p -e "require('./package.json').name")
  - export PKG_VERSION=$(node -p -e "require('./package.json').version")
  - npm install -g mkdirp
  - mkdirp ./dist -m 0777
  - mkdirp ./$PKG_NAME -m 0777
  - cp *.js package.json README.md LICENSE ./$PKG_NAME
  - cp -r ./db ./erd ./keymaps ./menus ./mssql ./mysql ./node_modules ./polyfill ./postgresql ./preferences ./util ./$PKG_NAME
  - zip -r ./dist/$PKG_NAME-$PKG_VERSION.zip ./$PKG_NAME

deploy:
  provider: releases
  api_key:
    secure: Ts3vSTRT+/8pc8LfK8af5zcxy4G8NvGfd7g4sQuOKiZGg1hPLHs2cMZbkWoQe7XgBSg7fZgUXEzH8yXYxAqwR9oLvxAB9LFnZyqt5tF47GEVPGpOKP2Q/QUqq+qDIWyfYLxjGi9iq8oxapgOisVOOsl1MHVJg/XkPPXmjnfr5C2q/EOPCnohQOlR3COXlyhEeO/UcAsVB7XqmpchZ5+uJBaoVL4KryeU0HoAvc6Pfd8YSDczz9xYWw7eGCbCHtQAS0AQerYe7LN5LIpz9tBQDJxyWIXQvEr4q1NGpbJZkoKHQEt4UWEmJyFSxM4jJnk0AhMwtN88f6siNf0G3HdZLdwC7A4CG1wHp0U6zrO3E48+u8GpuKwIMl/1vI4npmqrZY4+ffolxBT3OuGc+LVYuBj8/3AV8f/sb3r4r2aYoYlsk8PmZSQ/OU3cyN38m2JWtJRAhLNUn+9XYkTM9CFtY99NF3yyoL5Q2ktqvs6a/S6bcM10dwvfbPSDazCQoZ85Dv3ibyf9ZEMKClvCy6OrduVtNEDR+s4LOVIZQNJk/E+KGGGbVHe3YSrp7Be1kYdIHj+UMhfUJTDZMQXFrQuYmVcaXxEmRVaaFrv4MndE2kMtIG60H/m0YVTlP7QSfOCiuvJSy6k/Im53hcTXLV3mof+FZmAEPJ3EvSXpBnAOY2c=
  on:
    repo: kkrisz1/staruml-reverse-db
    tags: true
  file_glob: true
  file: dist/*
  skip_cleanup: false

cache:
  directories:
    - node_modules
